import type {
  AdminUserRecord,
  AnalyticsSummary,
  BasketData,
  DashboardData,
  PositionState,
} from "@/lib/types";

const disclaimer =
  "I am not a financial advisor. This system carries extreme risk of total or greater-than-account loss. Naked call and naked put selling with aggressive sizing up to 25% of account equity per name carries extreme risk. Always verify every price, chain, margin requirement, and order live on your broker platform before submitting any real trade. You alone are responsible for all outcomes.";

export const demoBaskets: BasketData[] = [
  {
    id: "basket-2026-03-30",
    title: "Weekly Basket — March 30, 2026 Entry",
    slug: "weekly-basket-2026-03-30",
    weekOf: "2026-03-30",
    publicationDate: "2026-03-30T13:34:00.000Z",
    status: "published",
    gsrs: 5.8,
    radarStatus: "Clean",
    cashNeeded: 60000,
    disclaimer,
    quickSummary: [
      { label: "GSRS", value: "5.8", hint: "Put-side restricted to 1% risk" },
      { label: "Cash Needed", value: "$60,000", hint: "4x leverage assumption" },
      { label: "Total Credit", value: "$27,100", hint: "Entry estimate" },
      { label: "Daily Theta", value: "$5,408", hint: "Estimated" },
    ],
    marketConditions: {
      gsrsNote:
        "GSRS remains in the 5–7 band. Put-side names are sized at 1% risk and doubles are prohibited.",
      vix: 31.05,
      skew: 144,
      hyOas: 3.17,
      move: 141,
      putCallRatio: 0.56,
      acquisitionRadarStatus: "Clean",
      downsideGapRadarStatus: "Clean",
      narrative:
        "Equity volatility remains elevated and cross-asset stress is above baseline, but the basket still supports selective short-premium exposure on both sides. Ford recall risk is treated as known and priced, while call-side takeover radar remains clear across the weak-name set.",
    },
    callPositions: [
      {
        id: "pos-hims",
        basketId: "basket-2026-03-30",
        side: "call",
        ticker: "HIMS",
        companyName: "Hims & Hers Health",
        sector: "Healthcare",
        entryUnderlyingPrice: 20.5,
        ivRank: 85,
        shortInterestPctFloat: 38,
        fanScore: 6.5,
        glassdoorScore: 3.2,
        buybackScore: 0,
        strike: 22,
        optionType: "call",
        expiry: "2026-04-04",
        delta: 0.18,
        estimatedEntryCredit: 0.3,
        contracts: 223,
        margin: 50000,
        breakAlert1: 21.2,
        breakAlert2: 21.8,
        thesisSummary:
          "High short interest, weak internal sentiment, and legal overhangs support call-side premium selling.",
        thesisBullets: [
          "Short interest above 38% of float",
          "Fan score below danger zone at 6.5",
          "Glassdoor at 3.2 with legal scrutiny",
          "No active buyback support",
        ],
        cautionFlags: ["FTC legal risk"],
        entryTimestamp: "2026-03-30T13:35:00.000Z",
        latestPerformance: {
          id: "snap-hims-2",
          observedAt: "2026-03-31T18:30:00.000Z",
          underlyingPrice: 20.74,
          optionMark: 0.24,
          confidence: "Actual",
          state: "safe",
          underlyingMovePct: 0.0117,
          distanceToStrike: 1.26,
          safetyBufferPct: 0.0607,
          daysToExpiry: 4,
          creditCapturePct: 0.2,
          pnlAmount: 1338,
          pnlPercent: 0.2,
          sourceLabel: "Yahoo option quote",
        },
        performanceHistory: [
          {
            id: "snap-hims-1",
            observedAt: "2026-03-30T13:35:00.000Z",
            underlyingPrice: 20.5,
            optionMark: 0.3,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 1.5,
            safetyBufferPct: 0.0732,
            daysToExpiry: 5,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-hims-2",
            observedAt: "2026-03-31T18:30:00.000Z",
            underlyingPrice: 20.74,
            optionMark: 0.24,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0.0117,
            distanceToStrike: 1.26,
            safetyBufferPct: 0.0607,
            daysToExpiry: 4,
            creditCapturePct: 0.2,
            pnlAmount: 1338,
            pnlPercent: 0.2,
            sourceLabel: "Yahoo option quote",
          },
        ],
      },
      {
        id: "pos-lcid",
        basketId: "basket-2026-03-30",
        side: "call",
        ticker: "LCID",
        companyName: "Lucid Group",
        sector: "Automotive",
        entryUnderlyingPrice: 10.2,
        ivRank: 88,
        shortInterestPctFloat: 32,
        fanScore: 5,
        glassdoorScore: 3.1,
        buybackScore: 0,
        strike: 11,
        optionType: "call",
        expiry: "2026-04-04",
        delta: 0.17,
        estimatedEntryCredit: 0.1,
        contracts: 476,
        margin: 50000,
        breakAlert1: 10.8,
        breakAlert2: 11,
        thesisSummary:
          "Balance sheet strain and dilution risk keep Lucid in the weak-name call-side bucket.",
        thesisBullets: [
          "Short interest above 30%",
          "Glassdoor below 3.2 with execution pressure",
          "No buyback support",
          "Acquisition radar remains clear",
        ],
        cautionFlags: ["Cash burn", "Saudi support watch"],
        entryTimestamp: "2026-03-30T13:35:00.000Z",
        latestPerformance: {
          id: "snap-lcid-2",
          observedAt: "2026-03-31T18:30:00.000Z",
          underlyingPrice: 10.41,
          estimatedOptionValue: 0.11,
          confidence: "Estimated",
          state: "approaching-strike",
          underlyingMovePct: 0.0206,
          distanceToStrike: 0.59,
          safetyBufferPct: 0.0567,
          daysToExpiry: 4,
          creditCapturePct: -0.1,
          pnlAmount: -476,
          pnlPercent: -0.1,
          sourceLabel: "Modeled from Yahoo chain IV proxy",
        },
        performanceHistory: [
          {
            id: "snap-lcid-1",
            observedAt: "2026-03-30T13:35:00.000Z",
            underlyingPrice: 10.2,
            optionMark: 0.1,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 0.8,
            safetyBufferPct: 0.0784,
            daysToExpiry: 5,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-lcid-2",
            observedAt: "2026-03-31T18:30:00.000Z",
            underlyingPrice: 10.41,
            estimatedOptionValue: 0.11,
            confidence: "Estimated",
            state: "approaching-strike",
            underlyingMovePct: 0.0206,
            distanceToStrike: 0.59,
            safetyBufferPct: 0.0567,
            daysToExpiry: 4,
            creditCapturePct: -0.1,
            pnlAmount: -476,
            pnlPercent: -0.1,
            sourceLabel: "Modeled from Yahoo chain IV proxy",
          },
        ],
      },
      {
        id: "pos-grpn",
        basketId: "basket-2026-03-30",
        side: "call",
        ticker: "GRPN",
        companyName: "Groupon",
        sector: "Consumer",
        entryUnderlyingPrice: 11.5,
        ivRank: 82,
        shortInterestPctFloat: 31,
        fanScore: 3,
        glassdoorScore: 3.3,
        buybackScore: 0,
        strike: 12.5,
        optionType: "call",
        expiry: "2026-04-04",
        delta: 0.16,
        estimatedEntryCredit: 0.12,
        contracts: 420,
        margin: 50000,
        breakAlert1: 12,
        breakAlert2: 12.3,
        thesisSummary:
          "Low fan support and operational softness make Groupon suitable for call-side exposure.",
        thesisBullets: [
          "Very low fan score at 3.0",
          "Layoffs and weak internal sentiment",
          "No buyback support",
          "Acquisition radar clean",
        ],
        cautionFlags: ["Low-float squeezes possible"],
        entryTimestamp: "2026-03-30T13:35:00.000Z",
        latestPerformance: {
          id: "snap-grpn-2",
          observedAt: "2026-03-31T18:30:00.000Z",
          underlyingPrice: 11.21,
          optionMark: 0.07,
          confidence: "Actual",
          state: "safe",
          underlyingMovePct: -0.0252,
          distanceToStrike: 1.29,
          safetyBufferPct: 0.1151,
          daysToExpiry: 4,
          creditCapturePct: 0.4167,
          pnlAmount: 2100,
          pnlPercent: 0.4167,
          sourceLabel: "Yahoo option quote",
        },
        performanceHistory: [
          {
            id: "snap-grpn-1",
            observedAt: "2026-03-30T13:35:00.000Z",
            underlyingPrice: 11.5,
            optionMark: 0.12,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 1,
            safetyBufferPct: 0.087,
            daysToExpiry: 5,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-grpn-2",
            observedAt: "2026-03-31T18:30:00.000Z",
            underlyingPrice: 11.21,
            optionMark: 0.07,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: -0.0252,
            distanceToStrike: 1.29,
            safetyBufferPct: 0.1151,
            daysToExpiry: 4,
            creditCapturePct: 0.4167,
            pnlAmount: 2100,
            pnlPercent: 0.4167,
            sourceLabel: "Yahoo option quote",
          },
        ],
      },
      {
        id: "pos-mara",
        basketId: "basket-2026-03-30",
        side: "call",
        ticker: "MARA",
        companyName: "MARA Holdings",
        sector: "Crypto",
        entryUnderlyingPrice: 9.8,
        ivRank: 90,
        shortInterestPctFloat: 30,
        fanScore: 6.5,
        glassdoorScore: 3.4,
        buybackScore: 0,
        strike: 10,
        optionType: "call",
        expiry: "2026-04-04",
        delta: 0.2,
        estimatedEntryCredit: 0.15,
        contracts: 495,
        margin: 50000,
        breakAlert1: 10.3,
        breakAlert2: 10.6,
        thesisSummary:
          "Crypto beta keeps MARA volatile, but the thesis still clears the weak-name filter set.",
        thesisBullets: [
          "Short interest right at 30%",
          "Bitcoin-correlated volatility remains elevated",
          "No buyback support",
          "Fan score remains below disqualifying zone",
        ],
        cautionFlags: ["Bitcoin headline sensitivity"],
        entryTimestamp: "2026-03-30T13:35:00.000Z",
        latestPerformance: {
          id: "snap-mara-2",
          observedAt: "2026-03-31T18:30:00.000Z",
          underlyingPrice: 10.11,
          estimatedOptionValue: 0.2,
          confidence: "Estimated",
          state: "approaching-strike",
          underlyingMovePct: 0.0316,
          distanceToStrike: -0.11,
          safetyBufferPct: -0.0109,
          daysToExpiry: 4,
          creditCapturePct: -0.3333,
          pnlAmount: -2475,
          pnlPercent: -0.3333,
          sourceLabel: "Modeled from Yahoo chain IV proxy",
        },
        performanceHistory: [
          {
            id: "snap-mara-1",
            observedAt: "2026-03-30T13:35:00.000Z",
            underlyingPrice: 9.8,
            optionMark: 0.15,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 0.2,
            safetyBufferPct: 0.0204,
            daysToExpiry: 5,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-mara-2",
            observedAt: "2026-03-31T18:30:00.000Z",
            underlyingPrice: 10.11,
            estimatedOptionValue: 0.2,
            confidence: "Estimated",
            state: "approaching-strike",
            underlyingMovePct: 0.0316,
            distanceToStrike: -0.11,
            safetyBufferPct: -0.0109,
            daysToExpiry: 4,
            creditCapturePct: -0.3333,
            pnlAmount: -2475,
            pnlPercent: -0.3333,
            sourceLabel: "Modeled from Yahoo chain IV proxy",
          },
        ],
      },
    ],
    putPositions: [
      {
        id: "pos-key",
        basketId: "basket-2026-03-30",
        side: "put",
        ticker: "KEY",
        companyName: "KeyCorp",
        sector: "Financials",
        entryUnderlyingPrice: 20.91,
        ivRank: 82,
        shortInterestPctFloat: 4.2,
        fanScore: 7.5,
        glassdoorScore: 3.7,
        buybackScore: 1,
        strike: 19,
        optionType: "put",
        expiry: "2026-04-04",
        delta: 0.15,
        estimatedEntryCredit: 0.15,
        contracts: 50,
        margin: 10000,
        atr14d: 0.7,
        buffer: "2x ATR OK",
        probabilityOfTouch: 0.3,
        thesisSummary:
          "Low short interest, active buyback support, and stable fundamentals keep KEY in the preferred put-side bucket.",
        thesisBullets: [
          "Short interest below 5%",
          "Buyback active",
          "Fan score 7.5 supports buy-the-dip behavior",
          "Downside-gap radar clean",
        ],
        cautionFlags: [],
        entryTimestamp: "2026-03-30T13:35:00.000Z",
        latestPerformance: {
          id: "snap-key-2",
          observedAt: "2026-03-31T18:30:00.000Z",
          underlyingPrice: 21.24,
          optionMark: 0.09,
          confidence: "Actual",
          state: "safe",
          underlyingMovePct: 0.0158,
          distanceToStrike: 2.24,
          safetyBufferPct: 0.1055,
          daysToExpiry: 4,
          creditCapturePct: 0.4,
          pnlAmount: 300,
          pnlPercent: 0.4,
          sourceLabel: "Yahoo option quote",
        },
        performanceHistory: [
          {
            id: "snap-key-1",
            observedAt: "2026-03-30T13:35:00.000Z",
            underlyingPrice: 20.91,
            optionMark: 0.15,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 1.91,
            safetyBufferPct: 0.0913,
            daysToExpiry: 5,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-key-2",
            observedAt: "2026-03-31T18:30:00.000Z",
            underlyingPrice: 21.24,
            optionMark: 0.09,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0.0158,
            distanceToStrike: 2.24,
            safetyBufferPct: 0.1055,
            daysToExpiry: 4,
            creditCapturePct: 0.4,
            pnlAmount: 300,
            pnlPercent: 0.4,
            sourceLabel: "Yahoo option quote",
          },
        ],
      },
      {
        id: "pos-hban",
        basketId: "basket-2026-03-30",
        side: "put",
        ticker: "HBAN",
        companyName: "Huntington Bancshares",
        sector: "Financials",
        entryUnderlyingPrice: 15.27,
        ivRank: 81,
        shortInterestPctFloat: 3.8,
        fanScore: 7.8,
        glassdoorScore: 3.6,
        buybackScore: 1,
        strike: 14,
        optionType: "put",
        expiry: "2026-04-04",
        delta: 0.15,
        estimatedEntryCredit: 0.1,
        contracts: 67,
        margin: 10000,
        atr14d: 0.5,
        buffer: "2x ATR OK",
        probabilityOfTouch: 0.3,
        thesisSummary:
          "Stable banking name with buyback support and disciplined social sponsorship makes HBAN a clean put-side hold.",
        thesisBullets: [
          "Short interest 3.8%",
          "Fan score above 7.5",
          "Earnings quality remains stable",
          "Buffer clears 2x ATR requirement",
        ],
        cautionFlags: [],
        entryTimestamp: "2026-03-30T13:35:00.000Z",
        latestPerformance: {
          id: "snap-hban-2",
          observedAt: "2026-03-31T18:30:00.000Z",
          underlyingPrice: 15.41,
          optionMark: 0.06,
          confidence: "Actual",
          state: "safe",
          underlyingMovePct: 0.0092,
          distanceToStrike: 1.41,
          safetyBufferPct: 0.0915,
          daysToExpiry: 4,
          creditCapturePct: 0.4,
          pnlAmount: 268,
          pnlPercent: 0.4,
          sourceLabel: "Yahoo option quote",
        },
        performanceHistory: [
          {
            id: "snap-hban-1",
            observedAt: "2026-03-30T13:35:00.000Z",
            underlyingPrice: 15.27,
            optionMark: 0.1,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 1.27,
            safetyBufferPct: 0.0832,
            daysToExpiry: 5,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-hban-2",
            observedAt: "2026-03-31T18:30:00.000Z",
            underlyingPrice: 15.41,
            optionMark: 0.06,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0.0092,
            distanceToStrike: 1.41,
            safetyBufferPct: 0.0915,
            daysToExpiry: 4,
            creditCapturePct: 0.4,
            pnlAmount: 268,
            pnlPercent: 0.4,
            sourceLabel: "Yahoo option quote",
          },
        ],
      },
      {
        id: "pos-f",
        basketId: "basket-2026-03-30",
        side: "put",
        ticker: "F",
        companyName: "Ford Motor Company",
        sector: "Automotive",
        entryUnderlyingPrice: 11.37,
        ivRank: 84,
        shortInterestPctFloat: 7.5,
        fanScore: 8.5,
        glassdoorScore: 3.8,
        buybackScore: 1,
        strike: 10,
        optionType: "put",
        expiry: "2026-04-04",
        delta: 0.16,
        estimatedEntryCredit: 0.08,
        contracts: 87,
        margin: 10000,
        atr14d: 0.4,
        buffer: "2x ATR OK",
        probabilityOfTouch: 0.32,
        thesisSummary:
          "Ford qualifies as a high-fan-score dip-buyer name despite elevated recall chatter.",
        thesisBullets: [
          "Fan score 8.5",
          "Active buyback support",
          "Short interest remains moderate",
          "Recall risk treated as known and priced",
        ],
        cautionFlags: ["2026 recall headline flow"],
        entryTimestamp: "2026-03-30T13:35:00.000Z",
        latestPerformance: {
          id: "snap-f-2",
          observedAt: "2026-03-31T18:30:00.000Z",
          underlyingPrice: 11.11,
          optionMark: 0.11,
          confidence: "Actual",
          state: "safe",
          underlyingMovePct: -0.0229,
          distanceToStrike: 1.11,
          safetyBufferPct: 0.0999,
          daysToExpiry: 4,
          creditCapturePct: -0.375,
          pnlAmount: -261,
          pnlPercent: -0.375,
          sourceLabel: "Yahoo option quote",
        },
        performanceHistory: [
          {
            id: "snap-f-1",
            observedAt: "2026-03-30T13:35:00.000Z",
            underlyingPrice: 11.37,
            optionMark: 0.08,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 1.37,
            safetyBufferPct: 0.1205,
            daysToExpiry: 5,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-f-2",
            observedAt: "2026-03-31T18:30:00.000Z",
            underlyingPrice: 11.11,
            optionMark: 0.11,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: -0.0229,
            distanceToStrike: 1.11,
            safetyBufferPct: 0.0999,
            daysToExpiry: 4,
            creditCapturePct: -0.375,
            pnlAmount: -261,
            pnlPercent: -0.375,
            sourceLabel: "Yahoo option quote",
          },
        ],
      },
      {
        id: "pos-pins",
        basketId: "basket-2026-03-30",
        side: "put",
        ticker: "PINS",
        companyName: "Pinterest",
        sector: "Communication Services",
        entryUnderlyingPrice: 17.76,
        ivRank: 80,
        shortInterestPctFloat: 14,
        fanScore: 7,
        glassdoorScore: 4.2,
        buybackScore: 1,
        strike: 15,
        optionType: "put",
        expiry: "2026-04-04",
        delta: 0.15,
        estimatedEntryCredit: 0.18,
        contracts: 56,
        margin: 10000,
        atr14d: 1,
        buffer: "2x ATR OK",
        probabilityOfTouch: 0.3,
        thesisSummary:
          "Pinterest remains the most fragile of the put-side names, but still clears buyback and fundamentals filters.",
        thesisBullets: [
          "Borderline short interest at 14%",
          "Glassdoor and revenue beats remain supportive",
          "Active buyback in place",
          "Mean-reversion buffer still holds",
        ],
        cautionFlags: ["Short-interest spike watch"],
        entryTimestamp: "2026-03-30T13:35:00.000Z",
        latestPerformance: {
          id: "snap-pins-2",
          observedAt: "2026-03-31T18:30:00.000Z",
          underlyingPrice: 18.02,
          estimatedOptionValue: 0.13,
          confidence: "Estimated",
          state: "safe",
          underlyingMovePct: 0.0146,
          distanceToStrike: 3.02,
          safetyBufferPct: 0.1676,
          daysToExpiry: 4,
          creditCapturePct: 0.2778,
          pnlAmount: 280,
          pnlPercent: 0.2778,
          sourceLabel: "Modeled from Yahoo chain IV proxy",
        },
        performanceHistory: [
          {
            id: "snap-pins-1",
            observedAt: "2026-03-30T13:35:00.000Z",
            underlyingPrice: 17.76,
            optionMark: 0.18,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 2.76,
            safetyBufferPct: 0.1554,
            daysToExpiry: 5,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-pins-2",
            observedAt: "2026-03-31T18:30:00.000Z",
            underlyingPrice: 18.02,
            estimatedOptionValue: 0.13,
            confidence: "Estimated",
            state: "safe",
            underlyingMovePct: 0.0146,
            distanceToStrike: 3.02,
            safetyBufferPct: 0.1676,
            daysToExpiry: 4,
            creditCapturePct: 0.2778,
            pnlAmount: 280,
            pnlPercent: 0.2778,
            sourceLabel: "Modeled from Yahoo chain IV proxy",
          },
        ],
      },
    ],
    meanReversionBuffer: [
      { label: "KEY", value: "$1.91", hint: "2x ATR requirement: $1.40" },
      { label: "HBAN", value: "$1.27", hint: "2x ATR requirement: $1.00" },
      { label: "F", value: "$1.37", hint: "2x ATR requirement: $0.80" },
      { label: "PINS", value: "$2.76", hint: "2x ATR requirement: $2.00" },
    ],
    portfolioSummary: {
      totalNames: 8,
      callCount: 4,
      putCount: 4,
      totalMargin: 240000,
      cashNeeded: 60000,
      totalEstimatedCredit: 27100,
      dailyTheta: 5408,
      concentrationNote: "Banking remains the largest group at ~8.3% of equity.",
      gsrsConstraintNote:
        "Put-side entries remain constrained to 1% risk until GSRS drops back below 5.",
    },
    orderBlocks: [
      {
        id: "ob-ibkr-calls",
        broker: "IBKR",
        side: "call",
        title: "IBKR TWS — Call Side",
        orderText:
          "Sell to Open 223 HIMS 2026-04-04 22 Call - Limit 0.30 - GTC - Portfolio Margin\nSell to Open 476 LCID 2026-04-04 11 Call - Limit 0.10 - GTC - Portfolio Margin\nSell to Open 420 GRPN 2026-04-04 12.50 Call - Limit 0.12 - GTC - Portfolio Margin\nSell to Open 495 MARA 2026-04-04 10 Call - Limit 0.15 - GTC - Portfolio Margin",
      },
      {
        id: "ob-ibkr-puts",
        broker: "IBKR",
        side: "put",
        title: "IBKR TWS — Put Side",
        orderText:
          "Sell to Open 50 KEY 2026-04-04 19 Put - Limit 0.15 - GTC - Portfolio Margin\nSell to Open 67 HBAN 2026-04-04 14 Put - Limit 0.10 - GTC - Portfolio Margin\nSell to Open 87 F 2026-04-04 10 Put - Limit 0.08 - GTC - Portfolio Margin\nSell to Open 56 PINS 2026-04-04 15 Put - Limit 0.18 - GTC - Portfolio Margin",
      },
      {
        id: "ob-schwab-calls",
        broker: "Schwab",
        side: "call",
        title: "Schwab StreetSmart Edge — Call Side",
        orderText:
          "Sell to Open 223 HIMS Apr 4 '26 $22 Call @ Limit 0.30\nSell to Open 476 LCID Apr 4 '26 $11 Call @ Limit 0.10\nSell to Open 420 GRPN Apr 4 '26 $12.50 Call @ Limit 0.12\nSell to Open 495 MARA Apr 4 '26 $10 Call @ Limit 0.15",
      },
      {
        id: "ob-schwab-puts",
        broker: "Schwab",
        side: "put",
        title: "Schwab StreetSmart Edge — Put Side",
        orderText:
          "Sell to Open 50 KEY Apr 4 '26 $19 Put @ Limit 0.15\nSell to Open 67 HBAN Apr 4 '26 $14 Put @ Limit 0.10\nSell to Open 87 F Apr 4 '26 $10 Put @ Limit 0.08\nSell to Open 56 PINS Apr 4 '26 $15 Put @ Limit 0.18",
      },
    ],
    priceAlerts: [
      {
        id: "alert-hims-1",
        positionId: "pos-hims",
        ticker: "HIMS",
        side: "call",
        label: "Break #1",
        thresholdValue: 21.2,
        protocolNote: "Double size if IV remains elevated.",
      },
      {
        id: "alert-hims-2",
        positionId: "pos-hims",
        ticker: "HIMS",
        side: "call",
        label: "Break #2",
        thresholdValue: 21.8,
        protocolNote: "Second double then mandatory full exit.",
      },
      {
        id: "alert-mara-1",
        positionId: "pos-mara",
        ticker: "MARA",
        side: "call",
        label: "Break #1",
        thresholdValue: 10.3,
        protocolNote: "Add risk only if IV remains rich.",
      },
      {
        id: "alert-put-restriction",
        ticker: "PUT SIDE",
        side: "put",
        label: "Restriction",
        thresholdValue: 5.8,
        protocolNote:
          "Put-side doubles remain prohibited while GSRS stays above 5.",
      },
    ],
    hardStops: [
      {
        id: "stop-1",
        category: "hard-stop",
        title: "25% loss on a single name",
        body: "Close the name immediately once mark-to-market loss reaches 25% of allocated risk.",
      },
      {
        id: "stop-2",
        category: "hard-stop",
        title: "30% portfolio drawdown",
        body: "Flatten the entire book if total portfolio drawdown reaches 30%.",
      },
      {
        id: "stop-3",
        category: "hard-stop",
        title: "Radar trigger",
        body: "Any credible acquisition or downside-gap catalyst triggers immediate full exit on the affected name.",
      },
    ],
    profitTargets: [
      {
        id: "target-1",
        category: "profit-target",
        title: "50–70% credit capture",
        body: "Primary exit target for each position once 50–70% of collected credit has been captured.",
      },
      {
        id: "target-2",
        category: "profit-target",
        title: "Daily 1% account gain",
        body: "Alternative portfolio-level profit target once the account reaches the daily 1% gain objective.",
      },
    ],
    freeformNotes: [
      "Put-side doubles remain blocked by GSRS.",
      "Ford recall risk remains a monitored flag rather than an outright disqualifier.",
      "MARA is the highest-velocity live warning and should stay on a high-priority watchlist.",
    ],
    adminOnlyNotes: [
      "If GSRS closes below 5, reopen consideration for normal put-side sizing next week.",
      "Monitor LCID and MARA for squeeze behavior into low-float headlines.",
    ],
    lastRefreshAt: "2026-03-31T18:30:00.000Z",
  },
  {
    id: "basket-2026-03-11",
    title: "Weekly Basket — March 11, 2026 Entry",
    slug: "weekly-basket-2026-03-11",
    weekOf: "2026-03-11",
    publicationDate: "2026-03-11T14:00:00.000Z",
    status: "archived",
    gsrs: 4.5,
    radarStatus: "Clean",
    cashNeeded: 100000,
    disclaimer,
    quickSummary: [
      { label: "GSRS", value: "4.5", hint: "Put-side halved" },
      { label: "Cash Needed", value: "$100,000" },
      { label: "Total Margin", value: "$200,000" },
      { label: "Theta", value: "$10k/day", hint: "Entry estimate" },
    ],
    marketConditions: {
      gsrsNote:
        "The system stayed in the 3–5 band, so put-side sizing was halved and doubles remained prohibited.",
      vix: 28.8,
      skew: 138,
      hyOas: 3.02,
      move: 126,
      putCallRatio: 0.61,
      acquisitionRadarStatus: "Clean",
      downsideGapRadarStatus: "Clean",
      narrative:
        "Macro stress was elevated but not dislocating. The March 11 basket leaned into two weak call-side biotech/data-center names and two cleaner regional-bank puts.",
    },
    callPositions: [
      {
        id: "pos-nvax",
        basketId: "basket-2026-03-11",
        side: "call",
        ticker: "NVAX",
        companyName: "Novavax",
        sector: "Biotech",
        entryUnderlyingPrice: 10.7,
        ivRank: 92,
        shortInterestPctFloat: 32,
        fanScore: 6,
        glassdoorScore: 3.1,
        buybackScore: 0,
        strike: 13,
        optionType: "call",
        expiry: "2026-03-18",
        delta: 0.18,
        estimatedEntryCredit: 0.45,
        contracts: 40,
        margin: 50000,
        breakAlert1: 11.8,
        breakAlert2: 12.5,
        thesisSummary: "Biotech squeeze risk stayed contained and the calls expired safely OTM.",
        thesisBullets: [
          "Short interest above 32%",
          "Litigation and operating stress",
          "No buyback support",
        ],
        cautionFlags: [],
        entryTimestamp: "2026-03-11T14:00:00.000Z",
        actualExitCredit: 0,
        latestPerformance: {
          id: "snap-nvax-2",
          observedAt: "2026-03-18T20:00:00.000Z",
          underlyingPrice: 11.34,
          optionMark: 0,
          confidence: "Expiry-Resolved",
          state: "expired-otm",
          underlyingMovePct: 0.0598,
          distanceToStrike: 1.66,
          safetyBufferPct: 0.1464,
          daysToExpiry: 0,
          creditCapturePct: 1,
          pnlAmount: 1800,
          pnlPercent: 1,
          sourceLabel: "Expiry settlement",
        },
        performanceHistory: [
          {
            id: "snap-nvax-1",
            observedAt: "2026-03-11T14:00:00.000Z",
            underlyingPrice: 10.7,
            optionMark: 0.45,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 2.3,
            safetyBufferPct: 0.2149,
            daysToExpiry: 7,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-nvax-2",
            observedAt: "2026-03-18T20:00:00.000Z",
            underlyingPrice: 11.34,
            optionMark: 0,
            confidence: "Expiry-Resolved",
            state: "expired-otm",
            underlyingMovePct: 0.0598,
            distanceToStrike: 1.66,
            safetyBufferPct: 0.1464,
            daysToExpiry: 0,
            creditCapturePct: 1,
            pnlAmount: 1800,
            pnlPercent: 1,
            sourceLabel: "Expiry settlement",
          },
        ],
      },
      {
        id: "pos-apld",
        basketId: "basket-2026-03-11",
        side: "call",
        ticker: "APLD",
        companyName: "Applied Digital",
        sector: "Technology",
        entryUnderlyingPrice: 12.5,
        ivRank: 88,
        shortInterestPctFloat: 31,
        fanScore: 5.5,
        glassdoorScore: 3.4,
        buybackScore: 0,
        strike: 15,
        optionType: "call",
        expiry: "2026-03-18",
        delta: 0.17,
        estimatedEntryCredit: 0.5,
        contracts: 35,
        margin: 50000,
        breakAlert1: 13.8,
        breakAlert2: 14.5,
        thesisSummary:
          "APLD stayed well behaved and decayed to nearly full capture before expiration.",
        thesisBullets: [
          "Short interest above 30%",
          "No active buyback",
          "Acquisition radar clean",
        ],
        cautionFlags: [],
        entryTimestamp: "2026-03-11T14:00:00.000Z",
        latestPerformance: {
          id: "snap-apld-2",
          observedAt: "2026-03-17T20:00:00.000Z",
          underlyingPrice: 12.87,
          optionMark: 0.04,
          confidence: "Actual",
          state: "safe",
          underlyingMovePct: 0.0296,
          distanceToStrike: 2.13,
          safetyBufferPct: 0.1655,
          daysToExpiry: 1,
          creditCapturePct: 0.92,
          pnlAmount: 1610,
          pnlPercent: 0.92,
          sourceLabel: "Actual close entered by admin",
        },
        performanceHistory: [
          {
            id: "snap-apld-1",
            observedAt: "2026-03-11T14:00:00.000Z",
            underlyingPrice: 12.5,
            optionMark: 0.5,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 2.5,
            safetyBufferPct: 0.2,
            daysToExpiry: 7,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-apld-2",
            observedAt: "2026-03-17T20:00:00.000Z",
            underlyingPrice: 12.87,
            optionMark: 0.04,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0.0296,
            distanceToStrike: 2.13,
            safetyBufferPct: 0.1655,
            daysToExpiry: 1,
            creditCapturePct: 0.92,
            pnlAmount: 1610,
            pnlPercent: 0.92,
            sourceLabel: "Actual close entered by admin",
          },
        ],
      },
    ],
    putPositions: [
      {
        id: "pos-key-hist",
        basketId: "basket-2026-03-11",
        side: "put",
        ticker: "KEY",
        companyName: "KeyCorp",
        sector: "Financials",
        entryUnderlyingPrice: 17,
        ivRank: 82,
        shortInterestPctFloat: 4.2,
        fanScore: 7.5,
        glassdoorScore: 3.7,
        buybackScore: 1,
        strike: 14,
        optionType: "put",
        expiry: "2026-03-18",
        delta: 0.15,
        estimatedEntryCredit: 0.35,
        contracts: 20,
        margin: 25000,
        atr14d: 0.7,
        buffer: "2x ATR OK",
        probabilityOfTouch: 0.3,
        thesisSummary: "KEY expired safely OTM with full capture.",
        thesisBullets: [
          "Buyback +1",
          "Short interest under 10%",
          "GSRS-constrained half size",
        ],
        cautionFlags: [],
        entryTimestamp: "2026-03-11T14:00:00.000Z",
        latestPerformance: {
          id: "snap-keyhist-2",
          observedAt: "2026-03-18T20:00:00.000Z",
          underlyingPrice: 17.91,
          optionMark: 0,
          confidence: "Expiry-Resolved",
          state: "expired-otm",
          underlyingMovePct: 0.0535,
          distanceToStrike: 3.91,
          safetyBufferPct: 0.2183,
          daysToExpiry: 0,
          creditCapturePct: 1,
          pnlAmount: 700,
          pnlPercent: 1,
          sourceLabel: "Expiry settlement",
        },
        performanceHistory: [
          {
            id: "snap-keyhist-1",
            observedAt: "2026-03-11T14:00:00.000Z",
            underlyingPrice: 17,
            optionMark: 0.35,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 3,
            safetyBufferPct: 0.1765,
            daysToExpiry: 7,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-keyhist-2",
            observedAt: "2026-03-18T20:00:00.000Z",
            underlyingPrice: 17.91,
            optionMark: 0,
            confidence: "Expiry-Resolved",
            state: "expired-otm",
            underlyingMovePct: 0.0535,
            distanceToStrike: 3.91,
            safetyBufferPct: 0.2183,
            daysToExpiry: 0,
            creditCapturePct: 1,
            pnlAmount: 700,
            pnlPercent: 1,
            sourceLabel: "Expiry settlement",
          },
        ],
      },
      {
        id: "pos-hban-hist",
        basketId: "basket-2026-03-11",
        side: "put",
        ticker: "HBAN",
        companyName: "Huntington Bancshares",
        sector: "Financials",
        entryUnderlyingPrice: 15.5,
        ivRank: 81,
        shortInterestPctFloat: 3.8,
        fanScore: 7.8,
        glassdoorScore: 3.6,
        buybackScore: 1,
        strike: 13,
        optionType: "put",
        expiry: "2026-03-18",
        delta: 0.15,
        estimatedEntryCredit: 0.4,
        contracts: 20,
        margin: 25000,
        atr14d: 0.5,
        buffer: "2x ATR OK",
        probabilityOfTouch: 0.3,
        thesisSummary: "HBAN was manually closed early at strong capture once the daily gain target was hit.",
        thesisBullets: [
          "Fan score remained above 7.5",
          "Clean buyback support",
          "Halved size due to GSRS band",
        ],
        cautionFlags: [],
        entryTimestamp: "2026-03-11T14:00:00.000Z",
        manualCloseDate: "2026-03-17",
        actualExitCredit: 0.08,
        latestPerformance: {
          id: "snap-hbanhist-2",
          observedAt: "2026-03-17T20:00:00.000Z",
          underlyingPrice: 15.72,
          optionMark: 0.08,
          confidence: "Actual",
          state: "manually-closed",
          underlyingMovePct: 0.0142,
          distanceToStrike: 2.72,
          safetyBufferPct: 0.173,
          daysToExpiry: 1,
          creditCapturePct: 0.8,
          pnlAmount: 640,
          pnlPercent: 0.8,
          sourceLabel: "Admin override",
        },
        performanceHistory: [
          {
            id: "snap-hbanhist-1",
            observedAt: "2026-03-11T14:00:00.000Z",
            underlyingPrice: 15.5,
            optionMark: 0.4,
            confidence: "Actual",
            state: "safe",
            underlyingMovePct: 0,
            distanceToStrike: 2.5,
            safetyBufferPct: 0.1613,
            daysToExpiry: 7,
            creditCapturePct: 0,
            pnlAmount: 0,
            pnlPercent: 0,
            sourceLabel: "Entry snapshot",
          },
          {
            id: "snap-hbanhist-2",
            observedAt: "2026-03-17T20:00:00.000Z",
            underlyingPrice: 15.72,
            optionMark: 0.08,
            confidence: "Actual",
            state: "manually-closed",
            underlyingMovePct: 0.0142,
            distanceToStrike: 2.72,
            safetyBufferPct: 0.173,
            daysToExpiry: 1,
            creditCapturePct: 0.8,
            pnlAmount: 640,
            pnlPercent: 0.8,
            sourceLabel: "Admin override",
          },
        ],
      },
    ],
    meanReversionBuffer: [
      { label: "KEY", value: "$3.00", hint: "2x ATR requirement: $1.40" },
      { label: "HBAN", value: "$2.50", hint: "2x ATR requirement: $1.00" },
    ],
    portfolioSummary: {
      totalNames: 4,
      callCount: 2,
      putCount: 2,
      totalMargin: 150000,
      cashNeeded: 100000,
      totalEstimatedCredit: 4050,
      dailyTheta: 10000,
      concentrationNote: "Exposure balanced between biotech/data infrastructure and regional banks.",
      gsrsConstraintNote: "Put-side doubledown protocol remained disabled for the full week.",
    },
    orderBlocks: [],
    priceAlerts: [],
    hardStops: [
      {
        id: "stop-hist-1",
        category: "hard-stop",
        title: "Single-name hard stop",
        body: "25% loss on any name forces closure.",
      },
    ],
    profitTargets: [
      {
        id: "target-hist-1",
        category: "profit-target",
        title: "Capture target",
        body: "Exit at 50–70% capture or when the daily target is satisfied.",
      },
    ],
    freeformNotes: [
      "This archived basket shows both expiry-resolved and actual closed outcomes.",
    ],
    lastRefreshAt: "2026-03-18T20:00:00.000Z",
  },
];

export const demoUsers: AdminUserRecord[] = [
  {
    id: "user-admin",
    email: "admin@polytheta.com",
    fullName: "Polytheta Admin",
    role: "admin",
    status: "active",
    identityConfirmedAt: "2026-03-01T12:00:00.000Z",
    acknowledgedRiskAt: "2026-03-01T12:05:00.000Z",
    lastLoginAt: "2026-03-31T17:55:00.000Z",
    createdAt: "2026-03-01T12:00:00.000Z",
  },
  {
    id: "user-member",
    email: "member@polytheta.com",
    fullName: "Sample Member",
    role: "member",
    status: "active",
    identityConfirmedAt: "2026-03-03T10:10:00.000Z",
    acknowledgedRiskAt: "2026-03-03T10:15:00.000Z",
    lastLoginAt: "2026-03-31T15:10:00.000Z",
    createdAt: "2026-03-03T10:10:00.000Z",
  },
];

export const demoSyncJobs = [
  {
    id: "sync-1",
    jobType: "market-refresh",
    status: "success" as const,
    startedAt: "2026-03-31T18:29:22.000Z",
    completedAt: "2026-03-31T18:30:04.000Z",
    positionsProcessed: 8,
    errorsCount: 0,
    notes: "4 exact option marks, 4 model-based estimates.",
  },
  {
    id: "sync-2",
    jobType: "entry-snapshot",
    status: "success" as const,
    startedAt: "2026-03-30T13:34:11.000Z",
    completedAt: "2026-03-30T13:35:12.000Z",
    positionsProcessed: 8,
    errorsCount: 0,
    notes: "Captured entry underlyings and baseline option marks.",
  },
];

export const demoDashboard = (): DashboardData => {
  const currentBasket = demoBaskets[0];
  const livePositions = [
    ...currentBasket.callPositions,
    ...currentBasket.putPositions,
  ];

  const warningPositions = livePositions.filter((position) =>
    ["approaching-strike", "breached"].includes(position.latestPerformance.state),
  );

  return {
    currentBasket,
    livePositions,
    warningPositions,
    latestRefreshAt: currentBasket.lastRefreshAt,
  };
};

export const demoAnalytics = (): AnalyticsSummary => {
  const positions = demoBaskets.flatMap((basket) => [
    ...basket.callPositions,
    ...basket.putPositions,
  ]);
  const statusCounts = positions.reduce(
    (map, position) => {
      const state = position.latestPerformance.state;
      map.set(state, (map.get(state) ?? 0) + 1);
      return map;
    },
    new Map<PositionState, number>(),
  );

  const averageCreditCapturePct =
    positions.reduce(
      (sum, position) => sum + position.latestPerformance.creditCapturePct,
      0,
    ) / positions.length;
  const estimatedPnl = positions.reduce(
    (sum, position) => sum + position.latestPerformance.pnlAmount,
    0,
  );

  return {
    basketsTracked: demoBaskets.length,
    livePositions: demoBaskets[0].callPositions.length + demoBaskets[0].putPositions.length,
    resolvedPositions:
      demoBaskets[1].callPositions.length + demoBaskets[1].putPositions.length,
    averageCreditCapturePct,
    estimatedPnl,
    statusCounts: Array.from(statusCounts.entries()).map(([state, count]) => ({
      state,
      count,
    })),
  };
};
