#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import postgres from 'postgres';
import { createBroker } from './index.mjs';
import { executionCycle } from './execution-engine.mjs';
import { readJournal, saveJournal } from './journal.mjs';
import { loadBrokerSettings } from '../lib/broker_settings.mjs';
import { acquireLock } from '../lib/file_lock.mjs';
import { scanRadar } from '../lib/news_radar.mjs';
import { currentWeek } from '../../shared/market-calendar.mjs';
const root = path.resolve(import.meta.dirname, '../..');
try { process.loadEnvFile(path.join(root, '.env.local')); } catch { /* environment may supply secrets */ }
const runtime = path.join(root, 'runtime'); fs.mkdirSync(runtime, { recursive: true, mode: 0o700 });
const release = acquireLock(path.join(runtime, '.execution.lock'));
process.once('exit', release);
const journalPath = path.join(runtime, 'ib-execution.json');
const checkOnly = process.argv.includes('--check');
const settings = await loadBrokerSettings();
const broker = createBroker(settings);
const enabled = !checkOnly && process.env.POLYTHETA_EXECUTION_ENABLED === 'true';
const journal = readJournal(journalPath);
const sql = postgres(process.env.NETLIFY_DATABASE_URL ?? process.env.DATABASE_URL, { max: 1 });
let connectedThisCycle = false;
try {
  const file = path.join(root, 'baskets', currentWeek(), 'data', 'basket_proposal.json');
  const proposal = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : null;
  const commands = enabled ? await sql`select value from app_settings where key like 'ib_exit:%' and value->>'status' in ('queued','monitoring') order by updated_at` : [];
  const result = await executionCycle({ broker, proposal, settings, journal, enabled,
    commands: commands.map(r => r.value),
    publish: async snapshot => {
      connectedThisCycle = true;
      await sql`insert into app_settings (key,value,updated_at) values ('broker_portfolio',${sql.json(snapshot)},now()) on conflict(key) do update set value=excluded.value,updated_at=now()`;
      for (const command of Object.values(journal.commands ?? {})) await sql`update app_settings set value=${sql.json(command)},updated_at=now() where key=${`ib_exit:${command.requestId}`}`;
    },
    save: value => saveJournal(journalPath, value),
    scanNews: async pick => {
      const result = await scanRadar([pick.ticker], null, { names: { [pick.ticker]: pick.name ?? '' } });
      if (result[pick.ticker].error) throw new Error(`News feed unavailable for ${pick.ticker}`);
      return result[pick.ticker][pick.side];
    },
  });
  const status = { ...result, account: undefined, connection: settings.connection, activated: enabled, checkedAt: new Date().toISOString(), fills: Object.keys(journal.fills).length };
  // Store diagnostics only. Account credentials and execution journal stay local.
  await sql`insert into app_settings (key,value,updated_at) values ('broker_status',${sql.json(status)},now()) on conflict(key) do update set value=excluded.value,updated_at=now()`;
  // Only verified fills generated by this service enter the actual ledger.
  for (const fill of Object.values(journal.fills)) {
    if (checkOnly) break;
    if (fill.commission == null || !Number.isFinite(fill.commission)) continue; // await commission, never invent zero fees
    if (!fill.time) continue;
    const at = new Date(fill.time);
    if (!Number.isFinite(+at)) continue; // broker timezone must be explicit
    // IB correction suffixes replace the original execution; they must not
    // create an additional ledger fill with a second UUID.
    const executionIdentity = fill.executionId.replace(/\.\d+$/, '');
    const hex = createHash('sha256').update(`IB:${broker.account}:${executionIdentity}`).digest('hex');
    const id = `${hex.slice(0,8)}-${hex.slice(8,12)}-5${hex.slice(13,16)}-a${hex.slice(17,20)}-${hex.slice(20,32)}`;
    const c = fill.contract;
    const note = `IB execution ${fill.executionId}; modeled credit ${fill.modeledCredit ?? 'n/a'}; execution service v1`;
    await sql`insert into trades (id,ticker,side,action,strike,expiry,quantity,price,fees,broker,executed_at,notes)
      values (${id},${c.symbol},${c.side},${fill.action === 'entry' ? 'sell-to-open' : 'buy-to-close'},${c.strike},${c.expiry},${fill.quantity},${fill.price},${fill.commission},'IBKR live',${at},${note})
      on conflict(id) do update set price=excluded.price,fees=excluded.fees,quantity=excluded.quantity,executed_at=excluded.executed_at,notes=excluded.notes,updated_at=now()`;
  }
  console.log(JSON.stringify(status));
} catch (error) {
  const message = String(error.message).replace(/\b(?:DU|U|F)\d{5,}\b/g, '[account]');
  const status = { connected: connectedThisCycle, connection: settings.connection, activated: enabled, message, checkedAt: new Date().toISOString() };
  await sql`insert into app_settings (key,value,updated_at) values ('broker_status',${sql.json(status)},now()) on conflict(key) do update set value=excluded.value,updated_at=now()`;
  console.error(message); process.exitCode = 1;
} finally { broker.disconnect(); await sql.end(); }
